console.log("===============================:To print from 5 to 15 number:============================");
for (let index = 5; index <=15; index++) {
    console.log(index);
    
}
console.log("==============================:To decrement number 50 to 40 number:================================================");

for (let num = 50; num >40; num--){
    console.log(num);
}
console.log("===========================:First 15 odd number: =======================================");
for(let num1=1;num1<30;num1++){
    if(num1%2!=0){
        console.log(num1);

    }
 
}
console.log("=================================================================================");
console.log("========================: printFirst 10 even numbe:r===============================");
var num=0;
for (let index = 0; index <=20; index++) {
    if (index%2==0) {
        console.log(index);
        num=num+1;
        if(num==10){
           break;
        }
        
    }

    
}
console.log("=======================================================");
console.log("===========================:to print 5 to 50 number:============================");
for (let index = 5; index <=50; index=index+5){
    console.log(index);
5   
}

console.log("========================:to print 10 to 100 number print :======================================");
for (let index = 10; index <=100; index=index+10) {
    console.log(index);
   
    
}

console.log("=============================:to reverse 100 to 10 dcreemnt number:========================================");

for (let reverse = 100; reverse >=10; reverse=reverse-10) {
   console.log(reverse);
    
}



























